/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import auxiliar.Mut;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import oovv.Examen;
import oovv.ExamenTest;
import oovv.ExamenTestResta;
import oovv.Maex;

/**
 *
 * @author Eduardo Silvestre
 */
public class DAfegeixExamen extends javax.swing.JDialog {

    /**
     * Creates new form DNota
     */
    public DAfegeixExamen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        tfNumPreguntes = new javax.swing.JTextField();
        bValida = new javax.swing.JButton();
        eNumPreguntes = new javax.swing.JLabel();
        eNumFalladesQresten = new javax.swing.JLabel();
        tfNumFalladesQResten = new javax.swing.JTextField();
        bCancela = new javax.swing.JButton();
        rbNormal = new javax.swing.JRadioButton();
        rbTest = new javax.swing.JRadioButton();
        tfData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfAssignatura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfAprovat = new javax.swing.JTextField();
        rbTestFR = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Data (dd/mm/aa)");

        tfNumPreguntes.setColumns(5);
        tfNumPreguntes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfNumPreguntes.setText("10");
        tfNumPreguntes.setEnabled(false);

        bValida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bValida.setText("valida");
        bValida.setActionCommand("valida normal");
        bValida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        eNumPreguntes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        eNumPreguntes.setForeground(new java.awt.Color(153, 153, 153));
        eNumPreguntes.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eNumPreguntes.setText("Nombre de Preguntes");

        eNumFalladesQresten.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        eNumFalladesQresten.setForeground(new java.awt.Color(153, 153, 153));
        eNumFalladesQresten.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        eNumFalladesQresten.setText("fallades resten un encert");

        tfNumFalladesQResten.setColumns(5);
        tfNumFalladesQResten.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfNumFalladesQResten.setText("10");
        tfNumFalladesQResten.setEnabled(false);

        bCancela.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bCancela.setText("cancel·la");
        bCancela.setActionCommand("cancela");
        bCancela.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        buttonGroup1.add(rbNormal);
        rbNormal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbNormal.setSelected(true);
        rbNormal.setText("normal");
        rbNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNormalActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTest);
        rbTest.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbTest.setText("test");
        rbTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTestActionPerformed(evt);
            }
        });

        tfData.setColumns(5);
        tfData.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Assignatura");

        tfAssignatura.setColumns(5);
        tfAssignatura.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Examen");

        tfAprovat.setColumns(5);
        tfAprovat.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfAprovat.setText("5");

        buttonGroup1.add(rbTestFR);
        rbTestFR.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbTestFR.setText("on les fallades resten");
        rbTestFR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTestFRActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Aprovat");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Examen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbNormal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAssignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAprovat, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eNumPreguntes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumPreguntes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNumFalladesQResten, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eNumFalladesQresten))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bValida)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bCancela))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbTest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbTestFR)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNormal)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfAssignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAprovat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbTest)
                    .addComponent(rbTestFR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNumPreguntes)
                    .addComponent(tfNumPreguntes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNumFalladesQResten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNumFalladesQresten))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bValida)
                    .addComponent(bCancela))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTestActionPerformed

        tfNumPreguntes.setEnabled(true);
        eNumPreguntes.setForeground(Color.BLACK);
        tfNumFalladesQResten.setEnabled(false);
        eNumFalladesQresten.setForeground(new java.awt.Color(153, 153, 153));
        bValida.setActionCommand("valida test");

    }//GEN-LAST:event_rbTestActionPerformed

    private void rbNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNormalActionPerformed

        tfNumPreguntes.setEnabled(false);
        eNumPreguntes.setForeground(new java.awt.Color(153, 153, 153));
        tfNumFalladesQResten.setEnabled(false);
        eNumFalladesQresten.setForeground(new java.awt.Color(153, 153, 153));
        bValida.setActionCommand("valida normal");

    }//GEN-LAST:event_rbNormalActionPerformed

    private void rbTestFRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTestFRActionPerformed

        tfNumPreguntes.setEnabled(true);
        eNumPreguntes.setForeground(Color.BLACK);
        tfNumFalladesQResten.setEnabled(true);
        eNumFalladesQresten.setForeground(Color.BLACK);
        bValida.setActionCommand("valida test resta");

    }//GEN-LAST:event_rbTestFRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DAfegeixExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DAfegeixExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DAfegeixExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DAfegeixExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DAfegeixExamen dialog = new DAfegeixExamen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancela;
    private javax.swing.JButton bValida;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel eNumFalladesQresten;
    private javax.swing.JLabel eNumPreguntes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton rbNormal;
    private javax.swing.JRadioButton rbTest;
    private javax.swing.JRadioButton rbTestFR;
    private javax.swing.JTextField tfAprovat;
    private javax.swing.JTextField tfAssignatura;
    private javax.swing.JTextField tfData;
    private javax.swing.JTextField tfNumFalladesQResten;
    private javax.swing.JTextField tfNumPreguntes;
    // End of variables declaration//GEN-END:variables

    public void setOidor(ActionListener oidor) {
        bCancela.addActionListener(oidor);
        bValida.addActionListener(oidor);
    }

    public Examen getExamenTR() throws Maex {
        double a = 0;
        try {
            a = Double.parseDouble(tfAprovat.getText());
        } catch (NumberFormatException ex) {
            throw new NumberFormatException("El valor de l'aprovat està entre 0 i 10");
        }
        int np = 0;
        try {
            np = Integer.parseInt(tfNumPreguntes.getText());
        } catch (NumberFormatException ex) {
            throw new NumberFormatException("El nombre de preguntes ha de ser major a 0");
        }
        int nf = 0;
        try {
            nf = Integer.parseInt(tfNumFalladesQResten.getText());
        } catch (NumberFormatException ex) {
            throw new NumberFormatException("El nombre de fallades que resten un encert ha de ser 1 com a mínim");
        }
        return new ExamenTestResta(nf, np,
                LocalDate.parse(tfData.getText(), Mut.DTF),
                tfAssignatura.getText(),
                a);
    }

    public Examen getExamenT() throws Maex {
        double a = 0;
        try {
            a = Double.parseDouble(tfAprovat.getText());
        } catch (NumberFormatException ex) {
            throw new NumberFormatException("El valor de l'aprovat està entre 0 i 10");
        }
        int np = 0;
        try {
            np = Integer.parseInt(tfNumPreguntes.getText());
        } catch (NumberFormatException ex) {
            throw new NumberFormatException("El nombre de preguntes ha de ser major a 0");
        }

        return new ExamenTest(np,
                LocalDate.parse(tfData.getText(), Mut.DTF),
                tfAssignatura.getText(),
                a);
    }

    public Examen getExamenN() throws Maex {
        double a = 0;
        try {
            a = Double.parseDouble(tfAprovat.getText());
        } catch (NumberFormatException ex) {
            throw new NumberFormatException("El valor de l'aprovat està entre 0 i 10");
        }

        return new Examen(LocalDate.parse(tfData.getText(), Mut.DTF),
                tfAssignatura.getText(),
                a);
    }

    public Examen getExamen() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


}
