/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.JMenuItem;

/**
 *
 * @author Eduardo Silvestre
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MiVentana
     */
    public FPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taPantalla = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miGuardaDades = new javax.swing.JMenuItem();
        miRecuperaDades = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miTancaApp = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miAfegeixExamen = new javax.swing.JMenuItem();
        miEsborraExamen = new javax.swing.JMenuItem();
        miAfegirNotes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miLlistaAlumnesNia = new javax.swing.JMenuItem();
        miLlistaAlumnesCognoms = new javax.swing.JMenuItem();
        miLlistaExamen = new javax.swing.JMenuItem();
        miLlistaUnExamen = new javax.swing.JMenuItem();
        miLlistaUnExamenOrdenat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taPantalla.setColumns(20);
        taPantalla.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        taPantalla.setRows(5);
        jScrollPane1.setViewportView(taPantalla);

        jMenu1.setText("Arxiu");

        miGuardaDades.setText("Guarda");
        jMenu1.add(miGuardaDades);

        miRecuperaDades.setText("Recupera");
        jMenu1.add(miRecuperaDades);
        jMenu1.add(jSeparator1);

        miTancaApp.setText("Tanca");
        jMenu1.add(miTancaApp);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Examen");

        miAfegeixExamen.setText("Afegeix");
        miAfegeixExamen.setActionCommand("Afegeix Examen");
        jMenu2.add(miAfegeixExamen);

        miEsborraExamen.setText("Esborra");
        miEsborraExamen.setActionCommand("Esborra Examen");
        jMenu2.add(miEsborraExamen);

        miAfegirNotes.setText("Afegeix notes");
        jMenu2.add(miAfegirNotes);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Llistat");

        miLlistaAlumnesNia.setText("Alumnes NIA");
        miLlistaAlumnesNia.setActionCommand("Llista Alumnes NIA");
        jMenu3.add(miLlistaAlumnesNia);

        miLlistaAlumnesCognoms.setText("Alumnes Cognoms");
        miLlistaAlumnesCognoms.setActionCommand("Llista Alumnes Cognoms");
        jMenu3.add(miLlistaAlumnesCognoms);

        miLlistaExamen.setText("Examens");
        miLlistaExamen.setActionCommand("Llista Examens");
        jMenu3.add(miLlistaExamen);

        miLlistaUnExamen.setText("Un examen");
        miLlistaUnExamen.setActionCommand("Llista Un Examen");
        jMenu3.add(miLlistaUnExamen);

        miLlistaUnExamenOrdenat.setText("Un examen Ord.");
        miLlistaUnExamenOrdenat.setActionCommand("Llista Un Examen Ordenat");
        jMenu3.add(miLlistaUnExamenOrdenat);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem miAfegeixExamen;
    private javax.swing.JMenuItem miAfegirNotes;
    private javax.swing.JMenuItem miEsborraExamen;
    private javax.swing.JMenuItem miGuardaDades;
    private javax.swing.JMenuItem miLlistaAlumnesCognoms;
    private javax.swing.JMenuItem miLlistaAlumnesNia;
    private javax.swing.JMenuItem miLlistaExamen;
    private javax.swing.JMenuItem miLlistaUnExamen;
    private javax.swing.JMenuItem miLlistaUnExamenOrdenat;
    private javax.swing.JMenuItem miRecuperaDades;
    private javax.swing.JMenuItem miTancaApp;
    private javax.swing.JTextArea taPantalla;
    // End of variables declaration//GEN-END:variables

    public void setOidor(ActionListener oidor) {
        JMenuItem[] items = {
            miAfegirNotes, miAfegeixExamen, miEsborraExamen,
            miLlistaAlumnesNia, miLlistaAlumnesCognoms, miLlistaExamen, 
            miLlistaUnExamen, miLlistaUnExamenOrdenat,
            miGuardaDades, miRecuperaDades, miTancaApp};
        for (JMenuItem item : items) {
            item.addActionListener(oidor);
        }
    }

    public void mostra(String text) {
        taPantalla.setText(text);
    }

}
